/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package seminarka;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Armaster
 */
public class databaze extends javax.swing.JPanel {

    /**
     * Creates new form databaze
     */
    public databaze() {
        initComponents();
        //soutl

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("medúza\npeklo\nFerrari\nvětroň\njahoda\nhokej\nhomogenní\nmutace\nchromozóm\nvojevůdce\nvolič\nvousy\nzbabělec\nbouřka\nodznak\nodpustit\nodrůda\núlomek\njablko\nponorka\nrogallo\nmetan\nkvarteto\nteflon\nparlament\npetrochemie");
        jTextArea1.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("bytost z řeckých bájí\nmísto zla\nznačka aut\nletadlo bez motoru\novoce\nsport\nstejnorodý\ngenetická  změna \nvláknitá struktura části buněčného jádra\nvojenský velitel\nčlověk účastnící se voleb\nporost brady\npříliš plachý člověk\natmosferický jev\npřipínáček za záslužnou činnost\nprominout\nnový druh rostliny\nkousek předmětu\nprvotní hřích (v mytologii)\npodmořské plavidlo\nsportovní létající zařízení\nzemní plyn\nčtyři hudebníci\npolytetrafluoretylen\nsbor zástupců lidu\nodvětví zpracování ropy");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("Slovo");

        jLabel2.setText("Nápověda");

        jLabel3.setText("Přidat další slovo");

        jLabel4.setText("a nápovědu");

        jButton1.setText("Přidat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("vymazat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Uložit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Načíst");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // vymazat
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // pridat

        int delkaSlova = this.jTextField1.getText().length();
        int delkaNapovedy = this.jTextField2.getText().length();

        if (delkaSlova > 12 | delkaSlova < 4 | delkaNapovedy == 0) {
            JOptionPane.showMessageDialog(null, "Délka slova musí být 4 až 12 znaků a nápověda nesmí být prázdná ", "Error", JOptionPane.ERROR_MESSAGE);
        } else {


            String dalsiSlovo = this.jTextField1.getText();
            String dalsiNapoveda = this.jTextField2.getText();
            this.jTextArea1.append("\r\n" + dalsiSlovo);
            this.jTextArea2.append("\r\n" + dalsiNapoveda);



        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // uložit

        Object[] volba = {"Yes", "No"};
        if (JOptionPane.showOptionDialog(this, "Opravdu chcete přemazat uloženou databázi?", "Uložení databáze", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, volba, volba[1]) == 0) {

            String nazevSouboru = "databaze.txt";
            String seznamSlov = this.jTextArea1.getText();
            String seznamNapoved = this.jTextArea2.getText();

            try {
                //pokusí se vytvořit soubor (zapsani skrs vstup)
                PrintWriter vystup = new PrintWriter(nazevSouboru);

                StringReader cteckaSouboruSl = new StringReader(seznamSlov);
                StringReader cteckaSouboruNa = new StringReader(seznamNapoved);
                BufferedReader cteckaRadkuSl = new BufferedReader(cteckaSouboruSl);
                BufferedReader cteckaRadkuNa = new BufferedReader(cteckaSouboruNa);
                String nextLineSl = "";
                String nextLineNa = "";

                while ((nextLineSl = cteckaRadkuSl.readLine()) != null | (nextLineNa = cteckaRadkuNa.readLine()) != null) {
                    vystup.println("" + nextLineSl);
                    vystup.println("" + nextLineNa);
                    vystup.println("// -----------------------------------");
                }

                cteckaSouboruSl.close();
                cteckaSouboruNa.close();
                cteckaRadkuSl.close();
                cteckaRadkuNa.close();
                vystup.close();

                System.out.println("Databáze uloženo do " + nazevSouboru);

            } catch (IOException a) {
                System.out.println("problem s vytvoreni souboru: " + nazevSouboru);
            }

            this.setVisible(false);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // načíst

        Object[] volba = {"Yes", "No"};
        String nazevSouboru = "databaze.txt";
        String radekNapovedy = "";
        String radekSlovo = "";
        int krok = 1;
        String seznamSlov = "";
        String seznamNapoved = "";


        if (JOptionPane.showOptionDialog(this, "Opravdu chcete přemazat zobrazená slova uloženým seznamem?", "Načtení databáze", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, volba, volba[1]) == 0) {
            //System.out.println("ano");

            try {
                this.jTextArea1.setText("");
                this.jTextArea2.setText("");
                FileReader cteckaSouboru = new FileReader(nazevSouboru);
                BufferedReader cteckaRadku = new BufferedReader(cteckaSouboru);
                String strLine;
                char znaky[] = new char[2];
                char pocet;
                while ((strLine = cteckaRadku.readLine()) != null) {   //precte radek 

                    pocet = strLine.charAt(0);                // zjisti prvni znak
                    if (pocet != '/') {                       // odfiltruje texty v napovede


                        if ((krok % 2) != 0) {
                            seznamSlov += strLine + "\r\n";
                        } else {
                            seznamNapoved += strLine + "\r\n";
                        }
                        krok++;

                    } else {
                        //System.out.println("tento radek je napoveda v souboru napoveda");
                    }

                } //konec while

                this.jTextArea1.setText(seznamSlov);
                this.jTextArea2.setText(seznamNapoved);
                System.out.println("Databáze načtena");


            } catch (Exception a) {
                System.out.println("chyba načtení databáze");
            }




        } else {
            //System.out.println("ne"); 
        }


    }//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
