/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package seminarka;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Armaster
 */
public class SibeniceHra extends javax.swing.JPanel {

    /**
     * Creates new form SibeniceHra
     */
    public static void main(String[] args) {
    }
    
    private String[] args;

    public SibeniceHra() {
        initComponents();
        //soutl

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("_");

        jButton1.setText("načíst slovo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0000.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0000.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("_");

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("_");

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("_");

        jTextField5.setEditable(false);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("_");

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("_");

        jTextField7.setEditable(false);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("_");

        jTextField8.setEditable(false);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("_");

        jTextField9.setEditable(false);
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("_");

        jTextField10.setEditable(false);
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("_");

        jTextField11.setEditable(false);
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("_");

        jTextField12.setEditable(false);
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("_");

        jLabel2.setText("zadaná písmena:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nápověda");

        jFormattedTextField1.setEditable(false);

        jFormattedTextField2.setEditable(false);

        jButton2.setText("Uložit hru");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Ferrary");
        jLabel4.setName(""); // NOI18N
        jLabel4.setVisible(false);

        jLabel5.setText("9");
        jLabel5.setVisible(false);

        jLabel6.setText("0");
        jLabel6.setVisible(false);

        jLabel7.setText("0");
        jLabel7.setVisible(false);

        jLabel8.setText("9");
        jLabel8.setVisible(false);

        jButton3.setText("Načíst hru");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //načíst slovo, poté zadat písmeno
        int hraZacala = Integer.parseInt(this.jLabel7.getText());
        String hadaneSlovo;
        int delkaSlova;


        if (hraZacala == 0) {

            typNastaveni nastaveniHry = loadNastaveni.main(args);               //nacteni nastaveni
            boolean nast_napoveda = nastaveniHry.getNast_napoveda();
            int nast_delkaSlov = nastaveniHry.getNast_delkaSlov();
            int nast_zivoty = nastaveniHry.getNast_zivoty();


            typSlovo nahodneSlovo1 = nahodneSlovo.main(args);                   // nacteni nahodneho slova

            jLabel3.setVisible(nast_napoveda);                      // zobrazeni napovedy
            jLabel3.setAutoscrolls(nast_napoveda);
            jLabel3.setText(nahodneSlovo1.getNapoveda());           // nápověda
            jLabel4.setText(nahodneSlovo1.getText());               // hádané slovo
            jLabel5.setText("" + nast_zivoty);                      // počet životů
            jLabel6.setText("0");                                   // počet uhádnutí
            jLabel7.setText("1");                                   // hra zacala (0 - 1)

            jButton1.setText("Zadat");
            jButton2.setEnabled(true);
            jFormattedTextField1.setEditable(true);


            hadaneSlovo = jLabel4.getText();
            //delkaSlova = hadaneSlovo.length();
            delkaSlova = nahodneSlovo1.getDelka();

            switch (delkaSlova) {
                case 3:
                    jTextField4.setVisible(false);
                case 4:
                    jTextField5.setVisible(false);
                case 5:
                    jTextField6.setVisible(false);
                case 6:
                    jTextField7.setVisible(false);
                case 7:
                    jTextField8.setVisible(false);
                case 8:
                    jTextField9.setVisible(false);
                case 9:
                    jTextField10.setVisible(false);
                case 10:
                    jTextField11.setVisible(false);
                case 11:
                    jTextField12.setVisible(false);
                    break;
                default:
                    break;
            }


        } else {                                                                //Start hry (hádání)

            String zadanaPismena1 = this.jFormattedTextField1.getText();        // aktuálně zadávané písmeno
            hadaneSlovo = jLabel4.getText();
            delkaSlova = hadaneSlovo.length();
            boolean pismenoBylo = false;
            char kontrolPismeno;
            boolean uhadl = false;
            int pocetZivotu = Integer.parseInt(jLabel5.getText());
            int pocetUhadnuti = Integer.parseInt(jLabel6.getText());
            String zadanaPismena0 = this.jFormattedTextField2.getText();        // jiz dríve zadane pismena
            int obrazek = Integer.parseInt(jLabel8.getText());

            if (zadanaPismena1.length() != 0) {

                char zadanePismeno = zadanaPismena1.charAt(0);                  // omezeni akt. zadávaného písmena
                int delkaZadanych = zadanaPismena0.length();
                int a = 0;
                int i = 0;

                if (delkaZadanych > 0) {                                        //-- kontrola zda písmeno již nebylo zadáno
                    while (a < delkaZadanych) {
                        kontrolPismeno = zadanaPismena0.charAt(a);

                        if (kontrolPismeno == zadanePismeno) {
                            System.out.println("Písmeno již bylo zadáno");
                            jFormattedTextField1.setText("");
                            pismenoBylo = true;
                        }
                        a++;
                    }
                }

                if (pismenoBylo == false) {
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    zadanaPismena0 += zadanePismeno;
                    this.jFormattedTextField2.setText(zadanaPismena0);        // zaznamenání zadaných písmen
                    while (i < delkaSlova) {

                        kontrolPismeno = hadaneSlovo.charAt(i);
                        //if (kontrolPismeno.equals(zadanePismeno)) //porovnani retezcu

                        if (kontrolPismeno == zadanePismeno) {
                            //System.out.println("uhadl jsi");
                            pocetUhadnuti += 1;
                            jLabel6.setText("" + pocetUhadnuti);

                            uhadl = true;

                            switch (i) {
                                case 0:
                                    this.jTextField1.setText("" + kontrolPismeno);
                                    this.jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 1:
                                    this.jTextField2.setText("" + kontrolPismeno);
                                    this.jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 2:
                                    this.jTextField3.setText("" + kontrolPismeno);
                                    this.jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 3:
                                    this.jTextField4.setText("" + kontrolPismeno);
                                    this.jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 4:
                                    this.jTextField5.setText("" + kontrolPismeno);
                                    this.jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 5:
                                    this.jTextField6.setText("" + kontrolPismeno);
                                    this.jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 6:
                                    this.jTextField7.setText("" + kontrolPismeno);
                                    this.jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 7:
                                    this.jTextField8.setText("" + kontrolPismeno);
                                    this.jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 8:
                                    this.jTextField9.setText("" + kontrolPismeno);
                                    this.jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 9:
                                    this.jTextField10.setText("" + kontrolPismeno);
                                    this.jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 10:
                                    this.jTextField11.setText("" + kontrolPismeno);
                                    this.jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                                case 11:
                                    this.jTextField12.setText("" + kontrolPismeno);
                                    this.jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
                                    break;
                            }

                        } else {
                            //System.out.println("neuhadl jsi");
                        }
                        i++;
                    }
                    if (uhadl == true) {
                        System.out.println("uhadl jsi");
                        this.jFormattedTextField1.setText("");
                        if (pocetUhadnuti == delkaSlova) {
                            System.out.println("Vyhrál jsi!");
                            JOptionPane.showMessageDialog(null, "Vyhrál jsi! ", "Výhra", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            jButton1.setEnabled(true);
                            jButton2.setEnabled(true);
                        }
                    } else {
                        System.out.print("neuhadl jsi, ");
                        this.jFormattedTextField1.setText("");
                        pocetZivotu -= 1;
                        jLabel5.setText("" + pocetZivotu);
                        System.out.println("zbývá ti " + pocetZivotu + " životů.");
                        

                        switch (pocetZivotu) {
                            case 0:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0009.jpg")));
                                jLabel8.setText("" + 0);
                                //this.jLabel1.setIcon(sib5_0009.jpg);
                                break;
                            case 1:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0007.jpg")));
                                jLabel8.setText("" + 1);
                                //this.jLabel1.setIcon(sib5_0007.jpg);
                                break;
                            case 2:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0006.jpg")));
                                jLabel8.setText("" + 2);
                                //this.jLabel1.setIcon(sib5_0006.jpg);
                                break;
                            case 3:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0005.jpg")));
                                jLabel8.setText("" + 3);
                                //this.jLabel1.setIcon(sib5_0005.jpg);
                                break;
                            case 4:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0004.jpg")));
                                jLabel8.setText("" + 4);
                                //this.jLabel1.setIcon(sib5_0004.jpg);
                                break;
                            case 5:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0003.jpg")));
                                jLabel8.setText("" + 5);
                                //this.jLabel1.setIcon(sib5_0003.jpg);
                                break;
                            case 6:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0002.jpg")));
                                jLabel8.setText("" + 6);
                                //this.jLabel1.setIcon(sib5_0002.jpg);
                                break;
                            case 7:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0001.jpg")));
                                jLabel8.setText("" + 7);
                                //this.jLabel1.setIcon(sib5_0001.jpg);
                                break;
                            case 8:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0000.jpg")));
                                jLabel8.setText("" + 8);
                                //this.jLabel1.setIcon(sib5_0000.jpg);
                                break;
                            default:
                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0000.jpg")));
                                jLabel8.setText("" + 9);
                                //this.jLabel1.setIcon(sib5_0000.jpg);
                                break;
                        }
                        
                        //------------------------------------------------------ probliknuti pismen
                        /*
                        this.jFormattedTextField2.setBackground(new java.awt.Color(255, 204, 204));
                        try{
                            this.wait(5);
                        } catch (Exception t) {
                          System.out.println("problem s čekáním");
                        }
                        this.jFormattedTextField2.setBackground(new java.awt.Color(255, 255, 255));
                        /**/
                        //------------------------------------------------------
                        
                        if (pocetZivotu <= 0) {
                            System.out.println("Prohrál jsi!");
                            JOptionPane.showMessageDialog(null, "Prohrál jsi! ", "Prohra", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            jButton1.setEnabled(true);
                            jButton2.setEnabled(true);
                        }
                    }
                }
            } else {
                System.out.println("nezadal jsi písmeno");
            }

        }
        
        jFormattedTextField1.requestFocus();                                    // dosadí kurzor do jFormattedTextField1
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // uložit

        String hadaneSlovo = jLabel4.getText();                             // hádané Slovo
        String napoveda = jLabel3.getText();                                // nápověda
        boolean nast_napoveda = jLabel3.getAutoscrolls();                   // zobrazena napovedy
        int pocetZivotu = Integer.parseInt(jLabel5.getText());              // počet životů
        int pocetUhadnuti = Integer.parseInt(jLabel6.getText());            // počet uhodnutí
        String zadanaPismena0 = this.jFormattedTextField2.getText();        // jiz dríve zadane pismena
        int obrazek = Integer.parseInt(jLabel8.getText());                  // zobrazeny obrázek

        String pi1 = jTextField1.getText();
        String pi2 = jTextField2.getText();
        String pi3 = jTextField3.getText();
        String pi4 = jTextField4.getText();
        String pi5 = jTextField5.getText();
        String pi6 = jTextField6.getText();
        String pi7 = jTextField7.getText();
        String pi8 = jTextField8.getText();
        String pi9 = jTextField9.getText();
        String pi10 = jTextField10.getText();
        String pi11 = jTextField11.getText();
        String pi12 = jTextField12.getText();




        String nazevSouboru = "ulozena hra " + 1 + ".txt";

        try {
            //pokusí se vytvořit soubor (zapsani skrs vstup)
            PrintWriter vystup = new PrintWriter(nazevSouboru);
            vystup.println("//hádané Slovo");
            vystup.println(hadaneSlovo);
            vystup.println("// nápověda");
            vystup.println(napoveda);
            vystup.println("// zobrazena napovedy");
            vystup.println(nast_napoveda);
            vystup.println("// počet životů");
            vystup.println(pocetZivotu);
            vystup.println("// počet uhodnutí");
            vystup.println(pocetUhadnuti);
            vystup.println("// jiz dríve zadane pismena");
            vystup.println(zadanaPismena0);
            vystup.println("// zobrazeny obrázek");
            vystup.println(obrazek);
            vystup.println("// písmeno 1");
            vystup.println(pi1);
            vystup.println("// písmeno 2");
            vystup.println(pi2);
            vystup.println("// písmeno 3");
            vystup.println(pi3);
            vystup.println("// písmeno 4");
            vystup.println(pi4);
            vystup.println("// písmeno 5");
            vystup.println(pi5);
            vystup.println("// písmeno 6");
            vystup.println(pi6);
            vystup.println("// písmeno 7");
            vystup.println(pi7);
            vystup.println("// písmeno 8");
            vystup.println(pi8);
            vystup.println("// písmeno 9");
            vystup.println(pi9);
            vystup.println("// písmeno 10");
            vystup.println(pi10);
            vystup.println("// písmeno 11");
            vystup.println(pi11);
            vystup.println("// písmeno 12");
            vystup.println(pi12);
            vystup.close();
            System.out.println("Hra uložena do: " + nazevSouboru);

        } catch (IOException a) {
            System.out.println("problem s vytvoreni souboru: " + nazevSouboru);
        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // načíst hru


        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jFormattedTextField1.setEditable(false);
        jButton1.setText("Zadat");
        jLabel7.setText("1");                                   // hra zacala (0 - 1)

        typUlozenaHra ulozenaHra = loadUlozenaHra.main(args);

        //---------------------------------------------------------------------- získání hodnot

        String hadaneSlovo = ulozenaHra.getHadaneSlovo();                       // hádané Slovo
        int delkaSlova = hadaneSlovo.length();
        String napoveda = ulozenaHra.getNapoveda();                             // nápověda
        boolean nast_napoveda = ulozenaHra.getNastNapoveda();
        int pocetZivotu = ulozenaHra.getPocetZivotu();                          // počet životů
        int pocetUhadnuti = ulozenaHra.getPocetUhadnuti();                      // počet uhodnutí
        String zadanaPismena = ulozenaHra.getZadanaPismena();                   // jiz dríve zadane pismena
        int obrazek = ulozenaHra.getObrazek();

        //---------------------------------------------------------------------- nastavení hodnot

        jLabel4.setText(hadaneSlovo);                                           // hádané Slovo
        jLabel3.setText(napoveda);                                              // nápověda
        jLabel3.setAutoscrolls(nast_napoveda);                                  // zobrazena napovedy
        jLabel3.setVisible(nast_napoveda);
        jLabel5.setText("" + pocetZivotu);                                        // počet životů
        jLabel6.setText("" + pocetUhadnuti);                                      // počet uhodnutí
        jFormattedTextField2.setText(zadanaPismena);                            // jiz dríve zadane pismena
        jLabel8.setText("" + obrazek);                                            // zobrazeny obrázek

        //---------------------------------------------------------------------- získání nastavení písmen
        String pi1 = ulozenaHra.getPi1();
        String pi2 = ulozenaHra.getPi2();
        String pi3 = ulozenaHra.getPi3();
        String pi4 = ulozenaHra.getPi4();
        String pi5 = ulozenaHra.getPi5();
        String pi6 = ulozenaHra.getPi6();
        String pi7 = ulozenaHra.getPi7();
        String pi8 = ulozenaHra.getPi8();
        String pi9 = ulozenaHra.getPi9();
        String pi10 = ulozenaHra.getPi10();
        String pi11 = ulozenaHra.getPi11();
        String pi12 = ulozenaHra.getPi12();

        this.jTextField1.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField2.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField3.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField4.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField5.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField6.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField7.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField8.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField9.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField10.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField11.setBorder(this.jFormattedTextField1.getBorder());
        this.jTextField12.setBorder(this.jFormattedTextField1.getBorder());

        if (!pi1.equals("_")) {
            this.jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi2.equals("_")) {
            this.jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi3.equals("_")) {
            this.jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi4.equals("_")) {
            this.jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi5.equals("_")) {
            this.jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi6.equals("_")) {
            this.jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi7.equals("_")) {
            this.jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi8.equals("_")) {
            this.jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi9.equals("_")) {
            this.jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi10.equals("_")) {
            this.jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi11.equals("_")) {
            this.jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }
        if (!pi12.equals("_")) {
            this.jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        }

        jTextField1.setText(pi1);
        jTextField2.setText(pi2);
        jTextField3.setText(pi3);
        jTextField4.setText(pi4);
        jTextField5.setText(pi5);
        jTextField6.setText(pi6);
        jTextField7.setText(pi7);
        jTextField8.setText(pi8);
        jTextField9.setText(pi9);
        jTextField10.setText(pi10);
        jTextField11.setText(pi11);
        jTextField12.setText(pi12);

        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField7.setVisible(true);
        jTextField8.setVisible(true);
        jTextField9.setVisible(true);
        jTextField10.setVisible(true);
        jTextField11.setVisible(true);
        jTextField12.setVisible(true);

        switch (delkaSlova) {
            case 3:
                jTextField4.setVisible(false);
            case 4:
                jTextField5.setVisible(false);
            case 5:
                jTextField6.setVisible(false);
            case 6:
                jTextField7.setVisible(false);
            case 7:
                jTextField8.setVisible(false);
            case 8:
                jTextField9.setVisible(false);
            case 9:
                jTextField10.setVisible(false);
            case 10:
                jTextField11.setVisible(false);
            case 11:
                jTextField12.setVisible(false);
                break;
            default:
                break;
        }

        //---------------------------------------------------------------------- nacteni obrazku

        switch (obrazek) {
            case 0:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0009.jpg")));
                break;
            case 1:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0007.jpg")));
                break;
            case 2:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0006.jpg")));
                break;
            case 3:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0005.jpg")));
                break;
            case 4:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0004.jpg")));
                break;
            case 5:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0003.jpg")));
                break;
            case 6:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0002.jpg")));
                break;
            case 7:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0001.jpg")));
                break;
            case 8:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0000.jpg")));
                break;
            default:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminarka/pic/sib5_0000.jpg")));
                break;
        }

        if (pocetZivotu >= 0) {                                                 // umožnení hry
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jFormattedTextField1.setEditable(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
